# Generated by Django 2.0.1 on 2018-01-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20180127_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
